# Generated by Django 5.2.1 on 2025-05-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp'], 'verbose_name': 'ข้อมูลเซนเซอร์', 'verbose_name_plural': 'ข้อมูลเซนเซอร์ทั้งหมด'},
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='source_id',
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='air_quality',
            field=models.FloatField(verbose_name='คุณภาพอากาศ'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(verbose_name='ความชื้น (%)'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(verbose_name='อุณหภูมิ (°C)'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='timestamp',
            field=models.DateTimeField(verbose_name='เวลาที่วัด'),
        ),
    ]
